"""
Order intent manager — v0.5.0.

Pre-trade idempotency layer. Every order the bot wants to place is
recorded here BEFORE any chain lookup or broker call. The intent_uuid
is generated by the bot (not the broker) so it survives reconnects:

- Paper engine: writes intent → executes against chain → marks ACKED
  immediately (paper has no async broker round-trip).
- Live engine (Phase 2.5+): writes intent → sends to IBKR → waits for
  acknowledgement → marks ACKED with permid. On reconnect, the
  reconciler reads PENDING + SUBMITTED rows and resolves them.

Status transitions:
    PENDING → SUBMITTED → ACKED      (happy path)
    PENDING → REJECTED               (risk gate or chain lookup failed)
    SUBMITTED → REJECTED             (broker rejected)
    SUBMITTED → ACKED                (fill received)

Reference: Stripe Idempotency-Key header semantics; IBKR ib_async
issues #80, #130, #308, #416 (duplicate-order failure modes on
reconnect).
"""
from __future__ import annotations

import json
import uuid
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from typing import Any, Literal

Status = Literal["PENDING", "SUBMITTED", "ACKED", "REJECTED"]


@dataclass(frozen=True)
class IntentRecord:
    """In-memory view of one bot_order_intents row."""
    intent_uuid: str
    signal_id: str | None
    strategy: str
    underlying: str
    direction: str
    intended_legs: list[dict[str, Any]]
    created_at: datetime
    status: Status
    permid: int | None
    order_ref: str | None
    submitted_at: datetime | None
    acked_at: datetime | None
    reject_reason: str | None


def create_intent(
    db, *,
    strategy: str,
    underlying: str,
    direction: str,
    intended_legs: list[dict[str, Any]],
    signal_id: str | None = None,
    intent_uuid: str | None = None,
) -> str:
    """
    Insert a PENDING intent. Returns the intent_uuid.

    If ``intent_uuid`` is supplied (caller-driven idempotency), the
    insert is a no-op when a row already exists. The CALLER must
    generate a fresh UUID per *trade idea*; passing the same UUID
    deduplicates retries.
    """
    iid = intent_uuid or str(uuid.uuid4())
    db.con.execute("""
        INSERT INTO bot_order_intents
        (intent_uuid, signal_id, strategy, underlying, direction,
         intended_legs_json, status)
        VALUES (?, ?, ?, ?, ?, ?, 'PENDING')
        ON CONFLICT (intent_uuid) DO NOTHING
    """, [iid, signal_id, strategy, underlying, direction,
          json.dumps(intended_legs)])
    return iid


def mark_submitted(db, intent_uuid: str, *,
                    order_ref: str, permid: int | None = None) -> None:
    """Move PENDING → SUBMITTED. Records the per-session order_ref."""
    db.con.execute("""
        UPDATE bot_order_intents
        SET status = 'SUBMITTED', order_ref = ?, permid = ?,
            submitted_at = ?
        WHERE intent_uuid = ? AND status = 'PENDING'
    """, [order_ref, permid, datetime.now(tz=timezone.utc), intent_uuid])


def mark_acked(db, intent_uuid: str, *,
                permid: int | None = None) -> None:
    """Move SUBMITTED → ACKED. permid is required for live; paper passes None."""
    db.con.execute("""
        UPDATE bot_order_intents
        SET status = 'ACKED', permid = COALESCE(?, permid),
            acked_at = ?
        WHERE intent_uuid = ? AND status IN ('PENDING', 'SUBMITTED')
    """, [permid, datetime.now(tz=timezone.utc), intent_uuid])


def mark_rejected(db, intent_uuid: str, *, reason: str) -> None:
    """Move PENDING/SUBMITTED → REJECTED with a human-readable reason."""
    db.con.execute("""
        UPDATE bot_order_intents
        SET status = 'REJECTED', reject_reason = ?
        WHERE intent_uuid = ? AND status IN ('PENDING', 'SUBMITTED')
    """, [reason, intent_uuid])


def get_intent(db, intent_uuid: str) -> IntentRecord | None:
    """Fetch one intent by UUID. None if not found."""
    row = db.con.execute("""
        SELECT intent_uuid, signal_id, strategy, underlying, direction,
               intended_legs_json, created_at, status, permid, order_ref,
               submitted_at, acked_at, reject_reason
        FROM bot_order_intents WHERE intent_uuid = ?
    """, [intent_uuid]).fetchone()
    if row is None:
        return None
    return IntentRecord(
        intent_uuid=row[0], signal_id=row[1], strategy=row[2],
        underlying=row[3], direction=row[4],
        intended_legs=json.loads(row[5]) if row[5] else [],
        created_at=row[6], status=row[7], permid=row[8],
        order_ref=row[9], submitted_at=row[10], acked_at=row[11],
        reject_reason=row[12],
    )


def unacked_intents(db, *, older_than_seconds: int = 30) -> list[IntentRecord]:
    """
    Intents PENDING or SUBMITTED older than ``older_than_seconds``.

    Used by the reconciler on every IBKR reconnect: anything in here
    is potentially orphaned (we said we wanted to trade but never
    heard back) and needs the IBKR open-orders / executions stream
    to determine actual state.
    """
    cutoff = datetime.now(tz=timezone.utc) - timedelta(seconds=older_than_seconds)
    rows = db.con.execute("""
        SELECT intent_uuid, signal_id, strategy, underlying, direction,
               intended_legs_json, created_at, status, permid, order_ref,
               submitted_at, acked_at, reject_reason
        FROM bot_order_intents
        WHERE status IN ('PENDING', 'SUBMITTED') AND created_at < ?
        ORDER BY created_at
    """, [cutoff]).fetchall()
    return [
        IntentRecord(
            intent_uuid=r[0], signal_id=r[1], strategy=r[2],
            underlying=r[3], direction=r[4],
            intended_legs=json.loads(r[5]) if r[5] else [],
            created_at=r[6], status=r[7], permid=r[8], order_ref=r[9],
            submitted_at=r[10], acked_at=r[11], reject_reason=r[12],
        )
        for r in rows
    ]


def count_by_status(db) -> dict[str, int]:
    """Counts per status — for the Bot Dashboard."""
    rows = db.con.execute("""
        SELECT status, COUNT(*) FROM bot_order_intents GROUP BY status
    """).fetchall()
    return {str(r[0]): int(r[1]) for r in rows}
