"""
PDF dossier export — printable equivalent of the PYPL strategy deck.

Structure mirrors ``~/Downloads/PYPL 80 LEAPS Strategy.pdf`` so a user
can hand the export to a peer and the format is recognised. Uses
``reportlab`` (pure Python, no system deps) so the export runs on the
same Streamlit Cloud / laptop the rest of VolScope runs on.

Single public entry: :func:`render_dossier_pdf`. Returns a bytes buffer
the Streamlit ``st.download_button`` can serve directly.

The footer carries the convergence score on the day the export was
generated, so a future re-run can compare ("on 2026-05-10 the score was 69").
"""
from __future__ import annotations

from datetime import date
from io import BytesIO
from typing import Optional

import pandas as pd

from volscope.analytics.leaps_convergence import (
    ConvergenceResult,
    LeapsSuggestion,
)
from volscope.analytics.leaps_pretrade import PretradeChecklist
from volscope.analytics.leaps_scenarios import (
    RiskTable,
    ScenarioMatrix,
    ThetaRunway,
    VegaGainTable,
)
from volscope.analytics.leaps_sizing import SizingPlan


# ── Public entry ─────────────────────────────────────────────────────────

def render_dossier_pdf(
    *,
    ticker: str,
    snapshot_date: date,
    convergence: ConvergenceResult,
    thesis: str,
    suggestion: LeapsSuggestion,
    sizing_plan: SizingPlan,
    risk_table: RiskTable,
    scenario_matrix: ScenarioMatrix,
    vega_table: VegaGainTable,
    theta_runway: ThetaRunway,
    pretrade: PretradeChecklist,
    underlying_row: pd.Series,
) -> bytes:
    """Render a single-ticker LEAPS dossier as a PDF byte stream.

    ``snapshot_date`` is recorded in the footer for reproducibility.
    All numerical inputs come from the live analytics pipeline; this
    function does no math of its own.
    """
    from reportlab.lib.colors import HexColor
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import mm
    from reportlab.platypus import (
        BaseDocTemplate, Frame, PageTemplate, Paragraph, Spacer, Table,
        TableStyle,
    )

    buffer = BytesIO()
    doc = BaseDocTemplate(
        buffer, pagesize=A4,
        leftMargin=18 * mm, rightMargin=18 * mm,
        topMargin=18 * mm, bottomMargin=18 * mm,
        title=f"VolScope LEAPS Dossier — {ticker}",
    )
    frame = Frame(
        doc.leftMargin, doc.bottomMargin,
        doc.width, doc.height,
        id="content",
    )

    def _draw_footer(canvas, doc_):
        canvas.saveState()
        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(HexColor("#888888"))
        canvas.drawString(
            doc.leftMargin, 10 * mm,
            f"VolScope LEAPS Dossier · {ticker} · convergence "
            f"{convergence.score:.0f} on {snapshot_date.isoformat()} · "
            f"page {doc_.page}",
        )
        canvas.drawRightString(
            A4[0] - doc.rightMargin, 10 * mm,
            "BSM-modelled premium — verify live bid/ask before trading",
        )
        canvas.restoreState()

    doc.addPageTemplates([PageTemplate(id="default", frames=[frame], onPage=_draw_footer)])

    styles = getSampleStyleSheet()
    h1 = ParagraphStyle("h1", parent=styles["Heading1"],
                        fontName="Helvetica-Bold", fontSize=20, leading=24,
                        textColor=HexColor("#0a0b0f"))
    h2 = ParagraphStyle("h2", parent=styles["Heading2"],
                        fontName="Helvetica-Bold", fontSize=13, leading=16,
                        textColor=HexColor("#0a0b0f"), spaceBefore=10, spaceAfter=4)
    body = ParagraphStyle("body", parent=styles["BodyText"],
                          fontName="Helvetica", fontSize=10, leading=14,
                          textColor=HexColor("#1f1f2e"))
    muted = ParagraphStyle("muted", parent=body,
                           textColor=HexColor("#6a6f7e"), fontSize=9)
    callout = ParagraphStyle("callout", parent=body,
                             leftIndent=10, borderPadding=8,
                             borderColor=HexColor("#00d4aa"),
                             borderWidth=2, borderRadius=4,
                             textColor=HexColor("#0a0b0f"))

    story: list = []

    # ── Title ──────────────────────────────────────────────────────────
    story.append(Paragraph(
        f"{ticker} — LEAPS Convergence Dossier", h1,
    ))
    story.append(Paragraph(
        f"Generated by VolScope on {snapshot_date.isoformat()} · "
        f"convergence score {convergence.score:.0f} / 100",
        muted,
    ))
    story.append(Spacer(1, 8))
    story.append(Paragraph(thesis, callout))
    story.append(Spacer(1, 6))

    # ── Anomaly read ───────────────────────────────────────────────────
    iv = underlying_row.get("iv_30d")
    hv = underlying_row.get("hv_20d")
    rank = underlying_row.get("iv_rank")
    perc = underlying_row.get("iv_percentile")
    iv_hv = (iv / hv) if (iv and hv and hv > 0) else None

    story.append(Paragraph("The anomaly — why options are mispriced", h2))
    anom_table_data = [
        ["Metric", "Value", "What it means"],
        ["IV (30d)", f"{iv:.1f}%" if iv is not None else "—",
         "Market's expected annualised σ"],
        ["HV (20d)", f"{hv:.1f}%" if hv is not None else "—",
         "Realised σ over the last month"],
        ["IV / HV", f"{iv_hv:.2f}" if iv_hv is not None else "—",
         "Below 1.00 = options cheaper than reality"],
        ["IV Rank (52w)", f"{rank:.0f}" if rank is not None else "—",
         "Position in 52w IV range — 0 = annual floor"],
        ["IV Pct (52w)", f"{perc:.0f}%" if perc is not None else "—",
         "Days in last year cheaper than today"],
    ]
    t = Table(anom_table_data, colWidths=[40 * mm, 35 * mm, doc.width - 75 * mm])
    t.setStyle(TableStyle([
        ("BACKGROUND",  (0, 0), (-1, 0), HexColor("#e6eef9")),
        ("TEXTCOLOR",   (0, 0), (-1, 0), HexColor("#0a0b0f")),
        ("FONTNAME",    (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE",    (0, 0), (-1, -1), 9),
        ("LINEBELOW",   (0, 0), (-1, 0), 0.5, HexColor("#cbd5e1")),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING",    (0, 0), (-1, -1), 4),
    ]))
    story.append(t)
    story.append(Spacer(1, 6))
    story.append(Paragraph(
        "Convergence sub-scores: "
        f"<b>Mispricing</b> {_fmt_score(convergence.mispricing)} · "
        f"<b>Neglect</b> {_fmt_score(convergence.neglect)} · "
        f"<b>Reversal</b> {_fmt_score(convergence.reversal)} "
        f"({convergence.coverage}/3 components present).",
        body,
    ))

    # ── Instrument ─────────────────────────────────────────────────────
    story.append(Paragraph("The instrument — strike, expiry, Greeks", h2))
    instr_data = [
        ["Strike", f"${suggestion.strike:.0f}"],
        ["Expiry", f"{suggestion.expiry.isoformat()} ({suggestion.days_to_exp}d)"],
        ["Premium (BSM est.)", f"${suggestion.est_premium:.2f}"],
        ["Breakeven", f"${suggestion.breakeven:.2f}"],
        ["Δ Delta",  f"{suggestion.delta:+.2f}"],
        ["Γ Gamma",  f"{suggestion.gamma:.4f}"],
        ["Θ /day",   f"{suggestion.theta_per_day:+.4f}"],
        ["ν / 1%",   f"{suggestion.vega_per_pct:+.3f}"],
    ]
    t = Table(instr_data, colWidths=[60 * mm, doc.width - 60 * mm])
    t.setStyle(TableStyle([
        ("FONTSIZE",      (0, 0), (-1, -1), 9),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ("TOPPADDING",    (0, 0), (-1, -1), 3),
        ("LINEBELOW",     (0, 0), (-1, -1), 0.25, HexColor("#e2e8f0")),
    ]))
    story.append(t)
    story.append(Paragraph(suggestion.rationale, muted))

    # ── Sizing + payoff ────────────────────────────────────────────────
    story.append(Paragraph("Position sizing + payoff at expiry", h2))
    sizing_summary = (
        f"Budget ${sizing_plan.budget:,.0f} · "
        f"{sizing_plan.contracts} contract"
        f"{'s' if sizing_plan.contracts != 1 else ''} · "
        f"deployed ${sizing_plan.capital_deployed:,.0f} · "
        f"max loss ${sizing_plan.max_loss:,.0f}"
    )
    story.append(Paragraph(sizing_summary, body))
    story.append(Spacer(1, 4))
    payoff_data = [["Spot at expiry", "P&L $", "Return %"]]
    for cell in sizing_plan.payoff:
        payoff_data.append([
            f"${cell.spot_at_expiry:,.2f}",
            f"${cell.profit_dollars:+,.0f}",
            f"{cell.return_pct:+.0f}%",
        ])
    t = Table(payoff_data, colWidths=[55 * mm, 50 * mm, doc.width - 105 * mm])
    t.setStyle(TableStyle([
        ("BACKGROUND",  (0, 0), (-1, 0), HexColor("#e6eef9")),
        ("FONTNAME",    (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE",    (0, 0), (-1, -1), 9),
        ("ALIGN",       (1, 1), (-1, -1), "RIGHT"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ("TOPPADDING",    (0, 0), (-1, -1), 3),
    ]))
    story.append(t)

    # ── Risk + scaling ─────────────────────────────────────────────────
    story.append(Paragraph("Risk · invalidation · scaling-in", h2))
    risk_data = [
        ["Max loss", f"${risk_table.max_loss_dollars:,.0f}"],
        ["Invalidation level", f"${risk_table.invalidation_spot:,.2f}"],
    ]
    t = Table(risk_data, colWidths=[60 * mm, doc.width - 60 * mm])
    t.setStyle(TableStyle([
        ("FONTSIZE",      (0, 0), (-1, -1), 9),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ("TOPPADDING",    (0, 0), (-1, -1), 3),
    ]))
    story.append(t)
    if risk_table.scaling_in_levels:
        scale_data = [["Spot trigger", "Add", "Rationale"]]
        for rung in risk_table.scaling_in_levels:
            scale_data.append([
                f"${rung.spot_trigger:,.2f}",
                f"+{rung.add_fraction*100:.0f}%",
                rung.rationale,
            ])
        t = Table(scale_data,
                  colWidths=[35 * mm, 25 * mm, doc.width - 60 * mm])
        t.setStyle(TableStyle([
            ("BACKGROUND",  (0, 0), (-1, 0), HexColor("#e6eef9")),
            ("FONTNAME",    (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE",    (0, 0), (-1, -1), 9),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ("TOPPADDING",    (0, 0), (-1, -1), 3),
            ("LINEBELOW",   (0, 0), (-1, 0), 0.5, HexColor("#cbd5e1")),
        ]))
        story.append(Spacer(1, 4))
        story.append(t)

    # ── Vega gain table ────────────────────────────────────────────────
    story.append(Paragraph("Vega gain — IV reverts today, spot unchanged", h2))
    vega_data = [["Target IV", "New premium", "P&L /contract", "% of premium"]]
    for r in vega_table.rows:
        vega_data.append([
            f"{r.target_iv*100:.0f}%",
            f"${r.new_premium:.2f}",
            f"${r.pnl_per_contract:+,.0f}",
            f"{r.pnl_pct_of_premium:+.0f}%",
        ])
    t = Table(vega_data, colWidths=[30 * mm, 35 * mm, 45 * mm, doc.width - 110 * mm])
    t.setStyle(TableStyle([
        ("BACKGROUND",  (0, 0), (-1, 0), HexColor("#e6eef9")),
        ("FONTNAME",    (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE",    (0, 0), (-1, -1), 9),
        ("ALIGN",       (1, 1), (-1, -1), "RIGHT"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ("TOPPADDING",    (0, 0), (-1, -1), 3),
    ]))
    story.append(t)

    if theta_runway.cliff_starts_at_month is not None:
        story.append(Paragraph(
            f"Theta cliff begins around month {theta_runway.cliff_starts_at_month}. "
            f"Roll or close the position before this point — daily decay at least "
            f"doubles past the cliff.",
            muted,
        ))

    # ── Pre-trade checklist ────────────────────────────────────────────
    story.append(Paragraph("Pre-trade checklist", h2))
    pt_data = [["Gate", "Level", "Notes"]]
    for r in pretrade.rows:
        pt_data.append([r.label, r.level, r.one_liner])
    t = Table(pt_data, colWidths=[40 * mm, 25 * mm, doc.width - 65 * mm])
    t.setStyle(TableStyle([
        ("BACKGROUND",  (0, 0), (-1, 0), HexColor("#e6eef9")),
        ("FONTNAME",    (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE",    (0, 0), (-1, -1), 9),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ("TOPPADDING",    (0, 0), (-1, -1), 3),
        ("LINEBELOW",   (0, 0), (-1, 0), 0.5, HexColor("#cbd5e1")),
    ]))
    story.append(t)

    if pretrade.order_templates:
        story.append(Paragraph("Order templates (paste into broker)", h2))
        for broker, text in pretrade.order_templates.items():
            story.append(Paragraph(f"<b>{broker}</b>", body))
            story.append(Paragraph(
                f"<font face='Courier' size='9'>{_escape_xml(text)}</font>",
                body,
            ))
            story.append(Spacer(1, 2))

    # ── Glossary ───────────────────────────────────────────────────────
    story.append(Paragraph("Glossary", h2))
    glossary = [
        ("Implied Volatility (IV)", "Market's expected annualised σ over the life of the option."),
        ("Historical Volatility (HV)", "Realised σ over a trailing window — typically 20 trading days."),
        ("IV / HV", "Sub-1.00 means options are pricing less movement than the stock has actually delivered."),
        ("IV Rank", "Today's IV mapped onto its 52w range. 0 = annual floor, 100 = annual ceiling."),
        ("Delta", "$ change in option value per $1 change in spot."),
        ("Vega", "$ change in option value per 1.00 change in σ. Per 1% change, divide by 100."),
        ("Theta", "$ change in option value per calendar day, all else equal."),
        ("Convexity", "Asymmetric payoff — capped loss equal to the premium, unbounded upside."),
    ]
    for term, defn in glossary:
        story.append(Paragraph(f"<b>{term}.</b> {defn}", body))
        story.append(Spacer(1, 1))

    doc.build(story)
    return buffer.getvalue()


# ── Helpers ──────────────────────────────────────────────────────────────

def _fmt_score(value: Optional[float]) -> str:
    return "—" if value is None else f"{value:.0f}"


def _escape_xml(s: str) -> str:
    return (
        s.replace("&", "&amp;")
         .replace("<", "&lt;")
         .replace(">", "&gt;")
    )


def filename_for(suggestion: LeapsSuggestion) -> str:
    """Conventional file name: ``LEAPS_PYPL_80_2028-05-09.pdf``."""
    return (
        f"LEAPS_{suggestion.ticker}_{int(suggestion.strike)}_"
        f"{suggestion.expiry.isoformat()}.pdf"
    )
